model_name: logistic_regression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LogisticRegression"

params:
  # penalty: ['l1', 'l2']
  solver: ["saga", "lbfgs", "liblinear"]
  max_iter: [100, 200, 1000]
  random_state: [88] #, 100, 44]
  C: [0.1, 0.5, 0.9]
  # C: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  # C: np.arange(0.1, 1, 0.1)

# hydra:
#   sweeper:
#     params:
#       +params.penalty: "'l1', 'l2'"
#       +params.solver: "'saga'"
#       +params.max_iter: "100, 200, 1000"
#       +params.random_state: 88
#       +params.C: range(start=0.1, stop=1, step=0.1)