defaults:
  - _self_

folds: 3

evaluation_metric: "f1"
cv_evaluation_metric: "mean_test_f1"

pyfunc_predict_fn: "predict_proba"

metrics:
  accuracy: "accuracy"
  f1: "f1"


# hydra:
#   sweeper:
#       sampler:
#         seed: 8888
#       # n_trials: 20 # number of times to try to optimize the search space
#       direction: maximize # minimize